### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [yaml/libyaml#106]
Hi libyaml,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by ingydotnet** [comment]
We currently have no private tracking system. If there is a serious concern to keep the vulnerability private, please email the concern to ingy@ingy.net. Otherwise create a GitHub issue here.

**Comment by Google-Autofuzz** [comment]
Great, thank you!
