### ISSUE TITLE
Document-End marker should always be emitted after block scalar with trailing empty lines

### ISSUE THREAD

**Issue by perlpunk** [yaml/libyaml#123]
The following YAML demonstrates a case where a document-end marker is important and should not be omitted:
```
foo: |+
  foo

...
```

libyaml should emit it even if `implicit` is true. Currently it does not, pyyaml and ruamel do.

Demo:
```
libyaml % echo '+STR
+DOC
=VAL |foo\n\n\n
-DOC
-STR' | ./tests/run-emitter-test-suite
|+
  foo


libyaml %
```

**Comment by perlpunk** [comment]
Related: https://github.com/yaml/yaml-test-suite/pull/49

**Comment by ingydotnet** [comment]
@perlpunk I think this should include blank lines as well. ie any trailing lines without visible characters.

**Comment by perlpunk** [comment]
@ingydotnet did you mean to comment this here? https://github.com/yaml/yaml-test-suite/issues/50
