### ISSUE TITLE
Cannot build without running "./bootstrap"

### ISSUE THREAD

**Issue by eschnett** [yaml/libyaml#137]
The README suggests that, after downloading the tarball for version 0.2.1, there should be a `configure` file that I can run. No such file exists, and I need to run `./bootstrap`. You might want to simplify your instructions respectively, since there doesn't seem to be a difference between building a git checkout and building from a release tarball.

**Comment by perlpunk** [comment]
Which tarball do you mean?
Here are the official release tarballs:
https://pyyaml.org/download/libyaml/
These are copies of the dist-x.y releases you can find her eon github.

We are currently looking into a possible problem with the 0.2.1 tarball, and 0.2.2 still needs to be built (the one you can download is just a tar archive of git).

**Comment by eschnett** [comment]
I was using the tarball from Github at <https://github.com/yaml/libyaml/archive/0.2.1.tar.gz>. Should I switch over to pyyaml.org?

(I see that the 0.2.2 tarball is much smaller than the 0.2.1; is that intended?)

**Comment by perlpunk** [comment]
Yes, the tarballs on github are just the git contents. They are automatically created.
We have a dist branch and put the distribution tarball contents in there, so downloding dist-0.2.1 should work for you, as well as https://pyyaml.org/download/libyaml/

I think I can tag the dist-0.2.2 later today.

**Comment by perlpunk** [comment]
Ok, this should be fixed now, thanks.
pyyaml.org is updated: https://pyyaml.org/download/libyaml/
the dist-0.2.2 tag here on github also: https://github.com/yaml/libyaml/archive/dist-0.2.2.tar.gz
