### ISSUE TITLE
Empty release - http://pyyaml.org/download/libyaml/yaml-0.2.2.tar.gz

### ISSUE THREAD

**Issue by rubyFeedback** [yaml/libyaml#139]
If you download:

http://pyyaml.org/download/libyaml/yaml-0.2.2.tar.gz

And e. g. try to repackage it, you get this:

tar -zxvf /Users/x/SRC/yaml/yaml-0.2.2.tar.gz -C /Depot/Temp/

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

If you then use file on it:

    file yaml-0.2.2.tar.gz 

You get:

yaml-0.2.2.tar.gz: HTML document, ASCII text, with no line terminators

Not sure what/where the problem is but previous releases worked fine; perhaps
something was automated but did not properly work. The .tar.gz but also the
.zip files do not appear to contain the code to yaml 0.2.2. The older releases
e. g. yaml-0.2.1.* still work fine. Just reporting this, feel free to close this at
any moment in time. :)

**Comment by perlpunk** [comment]
Oops, thanks. Downloading with `curl` apparently wasn't enough. Fixed!

**Comment by perlpunk** [comment]
I think I need to do a `make dist` to actually create a correct dist tarball. Will try...

**Comment by perlpunk** [comment]
correct tarball and zip are now uploaded, thanks
