### ISSUE TITLE
Not able to install LibYAML

### ISSUE THREAD

**Issue by AkashGS** [yaml/libyaml#145]
I followed all following steps but still not able to install :
1) git clone https://github.com/yaml/libyaml
2) ./bootstrap
3) ./configure
4) make
5) make install
When I run ./bootstrap command, I got the following error : "No such file or directory"

**Comment by lusianneDjepang** [comment]
Hi! I have the same problem!
Have you ever got solution? If yes, please, share it.
Thank you in advance

**Comment by perlpunk** [comment]
Is this the complete, exact error message you get?
I wouldn't know how to reproduce that.
Can you provide more information? On which platform are you running? And can you paste the complete and exact output?

**Comment by hSaria** [comment]
You need to change directory after cloning:
```
git clone https://github.com/yaml/libyaml
cd libyaml/
...
```

@AkashGS if this fixes it, mind closing the issue?

**Comment by perlpunk** [comment]
Please check the requirements listed in the README, especially the additional requirements needed for building from git.
If you have installed all requirements and still get the error message, please paste the exact output and reopen.
