### ISSUE TITLE
feature request and/or bug - problem: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Taulie0279** [yaml/libyaml#146]
i have a feature request - at same time it's a bug in the current version

i get this error message: "problem: mapping values are not allowed in this context"
with following yaml-source-code:
```
    crypt: true
        algorithm: AES
        key: abc
```
reason is the 'false'-value for 'crypt'.
with following yaml-source-code i don't get the error and it works the way i need it.
i want activate/deactive a group of key/value-pairs (this is my feature request)
```
    crypt: true
        # comment
        algorithm: AES
        # comment
        key: abc
```
this is working like a charm - but i want write you, because maybe its in next version an official feature - i hope so

greetz & best regards

thanks for the library

edit @perlpunk repair code markers

**Comment by perlpunk** [comment]
Can you provide some sample code?
for me your second example is not parsed by libyaml:
```
% cd libyaml
% cat example.yaml
crypt: true                                                                                                                                                                                     
    # comment
    algorithm: AES
    # comment
    key: abc
% tests/run-parser-test-suite < example.yaml
+STR
+DOC
+MAP
=VAL :crypt
=VAL :true
Parse error: did not find expected key
```

The second question is: What data structure does your example represent?
```
crypt: true
    algorithm: AES
    key: abc
```

Can you provide a corresponding JSON string? This is invalid YAML, and I don't know what you are trying to do.

**Comment by perlpunk** [comment]
I tested 14 YAML processors, and all say it's invalid.
C libyaml, C++ yaml-cpp, Java snakeyaml, PyYAML, ruamel, JS yaml, JS js-yaml, ruby psych, HsYAML, Lua yaml, Perl5 YAML.pm, Perl5 YAML::Syck, NimYAML, Perl5 YAML::PP

**Comment by Taulie0279** [comment]
i am wondering. i use C libyaml 0.2.2 from this repo.

our customer want support to enable/disable parts of a tree, so we can merge key-value-lists but we enable/disable outside of this file. i build a yaml-load-function, this function can load at runtime recursivly another yaml-file so we are able to build a default configuration and overwrite the customer configuration in a separate file.

for example:
default yaml is:
---
crypt: true
    algorithm: AES
    key: abc
---
customer yaml is:
---
yaml-load: 'default.yaml'
crypt: false
---
in this example the customer-yaml-file loads default-yaml-file by a special command and deactivates the crypt-functionality.

at the end we only see the values of interest in customer-yaml-file, not the detailed configuration.
in my implementation of libyaml i don't support all specs for now, like tags, but anchor, alias, merge  and so on works also from file to file and i found a solution for string concatenation. 
Here an example for string concat:
---
    node2: &node2 'C:\Temp'
    # test string concat
    node4: 'abc' *node2 '\abc'
    node5: *node2 '\abc' *node2
---
string concat we need to build paths. the root path is not of interest inside customer-yaml-file, because the installed system differs only in sub-folders or in parts of its name.

to your questions:
- i think its not compatible with json
- my data structures are objects they hold a key-value-pair and additionaly a child list of the same object

please think about these features for future release.
for me i need this functions, like string-concat. in my opinion every system need string-concat and value overwriting also a loading mechanism for other configuration files to hide values or sub-trees.

You can close that ticket, if that are not good features for you. But i googled for "yaml string concat" and recursive loading and many people asked for it or programmed special tag-function or something else. 

thanks for your attention

greetz

**Comment by perlpunk** [comment]
Your two YAML examples are invalid YAML.

Can you please show a small program that can parse this with libyaml?
I showed you https://github.com/yaml/libyaml/blob/master/tests/run-parser-test-suite.c


I don't understand this sentence: "our customer want support to enable/disable parts of a tree".

> in my opinion every system need string-concat

YAML is a serialization language and not a programmin language.

> value overwriting also a loading mechanism for other configuration files to hide values or sub-trees

You can write an `!include` tag handler if you want.

Also you could write your own `!merge` tag handler that merges mappings like you would expect. Merging mappings is not trivial. Should repeated keys be overriden or ignored. Should it merge recursively? What about sequences (e.g. the first value is a sequene and the second one two. Would you concatenate the two sequences if you merge it?).

In any case, it won't be possible with the syntax you show. It's simply invalid.

Show your code first (and not only your YAML).

**Comment by perlpunk** [comment]
Could it be that you are just stopping the parser once you have all the data you need? That would explain why you dont get an error.
If that's the case, your approach would stop working as soon as there is other data you need after the invalid block:
```
crypt: true
    # comment
    algorithm: AES
    # comment
    key: abc
some: other data
```

**Comment by perlpunk** [comment]
Or could it be that you are just using `yaml_parser_scan()` and not `yaml_parser_parse()`?
I'd say in that case you are mostly on your own. `yaml_parser_scan()` does only scan tokens, but it does not do any parsing, that's why it won't always give you an error, where the parser would.

**Comment by Taulie0279** [comment]
you come from Berlin...
dann könne wir auch deutsch reden.

Ich benutze libyaml 0.2.2 und ich bin weit weg von der geforderten Spezifikation. Ich lasse die yaml parsen und packe alles in eine Klasse die key, value und eine Childliste hat, also mapping und sequenzen sind bei mir das gleiche. Es sind für mich listen aus childs ohne key. Den gesamten Code kann ich hier leider nicht posten, da ich eine unser Kunde wie schon erwähnt ein global Player ist und ich mich schriftlich zur Verschwiegenheit verpflichtet habe.

Ich habe mich nach einem Beispiel gerichtet, welches in online gefunden habe und der Code verwendet tatsächlich yaml_parser_scan(). Dann wird es wohl daran liegen.
Mein Feature-Request hat die Intention den Parser zu verbessern. ... Ich arbeite schon viele viele Jahre als Softwareentwickler und in jeder Konfigurationdatei benötigte ich bisher immer eine String-Concatenation um die Konfiguration zu splitten, zusammenzuführen und/oder zu kaskadieren, es kam jetzt die Anforderung eben auch externe bzw. unter- oder übergeordnete Konfigurationsdateien zu laden. Da ich auch mit Java zu tun habe und ich aufgrund der Projekte mit yaml zu tun hatte, hat mich die Syntax und Sematik überzeugt. Bisher verwenden wir in diesem Projekt ini-Dateien, also key/value-listen denen wir beim Key ein Präfix vorangestellt haben um die viele Prozesse konfigurieren zu können. Diese Tatsache habe ich jetzt durch die Baumstruktur der yaml-Dateien aufgebrochen, was die gesamte Konfiguration übersichtlicher macht. Damit unser Kunde eine Standardkonfiguration laden kann existiert jetzt eine Funktion die andere yaml-Dateien rekursiv lädt und in meinen Konfigurationsbaum einfügt.

Wie du schon erwähnt hast, kann ich ein tag hinzufügen der z.B. Strings zusammenführt, habe ich so gemacht. das Rekursive Laden funktioniert auch super. Es leider nur etwas nervig, dass ich vor den Keys ein Kommentar einbauen muss, damit das ganze funktioniert wie ich es brauche. Aber ich kann damit leben. 

Wenn die Intention des Projektes ist, kompatibel zu JSON zu bleiben, dann kann der Feature-Request auch nicht eingebaut werden und sollte auch nicht in den Standard eingebaut werden. Ich war mir dessen nicht bewusst. Also meine Unwissenheit. Für mich ist wichtig, dass ich mein aktuelles Projekt umsetzen kann und das geht auch mit meiner aktuellen Implementation.

Also nochmals vielen Dank für Deine Mühe.

PS: Vielleicht macht es Sinn Standard-tags einzubauen für Funktionalitäten die man in der Praxis zusätzlich braucht.

Du kannst den Issue gern schliessen. Danke.
