### ISSUE TITLE
luke: fatal: required symbol 'yaml_document_initialize' not found in any of libc, libyaml

### ISSUE THREAD

**Issue by balajipothula** [yaml/libyaml#156]
git clone https://github.com/yaml/libyaml.git
sudo yum -y install gcc libtool make
cd libyaml/
./bootstrap
./configure
make
sudo make install

luarocks install lyaml

ERROR:
Installing https://luarocks.org/lyaml-6.2.4-1.src.rock

/home/ec2-user/lua/bin/lua build-aux/luke package="lyaml" version="6.2.4" PREFIX="/home/ec2-user/luarocks/lib/luarocks/rocks-5.1/lyaml/6.2.4-1" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" LUA="/home/ec2-user/lua/bin/lua" LUA_DIR="/home/ec2-user/luarocks/lib/luarocks/rocks-5.1/lyaml/6.2.4-1/lua" LUA_INCDIR="/home/ec2-user/lua/include" YAML_DIR="/usr/local" YAML_INCDIR="/usr/local/include" YAML_LIBDIR="/usr/local/lib"
luke: fatal: required symbol 'yaml_document_initialize' not found in any of libc, libyaml

Error: Build error: Failed building.

**Comment by thg303** [comment]
any solution for this?

**Comment by thg303** [comment]
looks like it's because of lyaml implementation. [check this out](https://github.com/gvvaughan/lyaml/issues/30) for more details and a work-around.

**Comment by perlpunk** [comment]
I tried on ubuntu 18.04 and it works for me.
So maybe this was fixed in lyaml and can be closed?
