### ISSUE TITLE
authority concerns on trade issues about US EAR

### ISSUE THREAD

**Issue by ilikelucifer** [yaml/libyaml#163]
We are concerned about the authority of YAML as recently arised trade issues between US and the rest of the world (especially China). We are looking forward to get your official answers for the questions below:
1. Is the YAML project subject to U.S. Export Administration Regulations (EAR) and classified under ECCN 0D521? Or such AI software is subject to EAR, but not classified under ECCN 0D521? 
2.  Is U..S. Bureau of Industry and Security license required for exporting this project to China？

**Comment by peterkmurphy** [comment]
@ilikelucifer : [YAML](https://yaml.org/spec/1.2/spec.html) is a data serialization language, similar in ideas to such thing as JSON and XML. The spec is hosted elsewhere. You are opening an issue on _libyaml_, a parser for YAML files. YAML has nothing to do with [ECCN 0D521](https://www.federalregister.gov/documents/2020/01/06/2019-27649/addition-of-software-specially-designed-to-automate-the-analysis-of-geospatial-imagery-to-the-export), which is about:

> Geospatial imagery “software” “specially designed” for training a Deep Convolutional Neural Network to automate the analysis of geospatial imagery and point clouds

But libyaml is definitely not an AI. It's a tool that reads text files - not image files - looking for YAML-formatted content, without any capacity for understanding ambiguity or "getting" where the YAML author comes from. It is common for the tool to throw an exception if one character - be it a colon or even a space - is out of place.

**Comment by peterkmurphy** [comment]
As for _U.S. Export Administration Regulations_...  seriously, I have no clue, but as I said: YAML is a data serialization technology, and not as sexy as [topics](https://www.bis.doc.gov/index.php/regulations/export-administration-regulations-ear) such as "Materials Chemicals Microorganisms and Toxins". 

Just remember that libyaml is hosted at GitHub, an American site bound by [American Trade Controls](https://help.github.com/en/github/site-policy/github-and-trade-controls). So if it ok to host it here, it is also ok to use it in products outside the US.

**Comment by ilikelucifer** [comment]
> As for _U.S. Export Administration Regulations_... seriously, I have no clue, but as I said: YAML is a data serialization technology, and not as sexy as [topics](https://www.bis.doc.gov/index.php/regulations/export-administration-regulations-ear) such as "Materials Chemicals Microorganisms and Toxins".
> 
> Just remember that libyaml is hosted at GitHub, an American site bound by [American Trade Controls](https://help.github.com/en/github/site-policy/github-and-trade-controls). So if it ok to host it here, it is also ok to use it in products outside the US.

Thanks, I got it. Very appreciate for your work.

**Comment by perlpunk** [comment]
I guess this can be closed?
