### ISSUE TITLE
Handle duplicate dict keys

### ISSUE THREAD

**Issue by kontur** [yaml/libyaml#166]
A yaml file `foobar.yaml` like this:

```
foo:
    bar: 0
    bar: 1
```

parsed like this:

```
import yaml
with open("foobar.yaml") as f:
    data = yaml.load(f, Loader=yaml.Loader)
    print(data)
```

will output:

```
{'foo': {'bar': 1}}
```

In my opinion loading this yaml file should either fail altogether or at least emit a warning about the encountered duplicate key. Now there is no way to know or validate that a yaml file does not contain duplicate keys. As can be seen, incidentally the last attribute of the `bar` name is taken as the value.

**Comment by i-ky** [comment]
> Now there is no way to know or validate that a yaml file does not contain duplicate keys.

I guess there is such possibility if you use C API directly. What you are talking about is an issue of Python module and, I guess, it should be reported elsewhere.

**Comment by kontur** [comment]
Oh, sorry! I followed the pyaml documentation page links, but totally missed this was not an implementation specific repo. Will close and reopen where more appropriate.
