### ISSUE TITLE
YAML_STATIC_LIB_NAME should be a cached var, not an option

### ISSUE THREAD

**Issue by bartgol** [yaml/libyaml#167]
In cmake, the `OPTION` command is basically creating a cache variable with type BOOL. However, the static lib name should be a string. In fact, when building libyaml, I get that the library name is `OFF`, probably due to how cmake converts the provided default `yaml` to a bool (although I would have expected the conversion to yield ON).

I suggest replacing the line
```
option(YAML_STATIC_LIB_NAME "base name of static library output" yaml)
```
with
```
set(YAML_STATIC_LIB_NAME yaml CACHE STRING "base name of static library output") 
```

I can fork and submit a quick PR, if you like.

**Comment by perlpunk** [comment]
Thanks! I merged PR #157
