### ISSUE TITLE
Clarify error for peculiar alias naming

### ISSUE THREAD

**Issue by headius** [yaml/libyaml#205]
In jruby/jruby#6365 we received a report of JRuby's YAML library producing a different error than the one used by CRuby.

JRuby uses SnakeYAML while CRuby uses libyaml.

The case in question involves the following content:

```yaml
Exclude: **/*_old.rb
```

On libyaml (and older SnakeYAML), this is rejected as a syntax error because the `*` is interpreted as an alias prefix and the rest of the string does not conform to (typical?) alias naming (error raised is a syntax error).

On recent SnakeYAML, this parses ok but is rejected as a missing alias (error raised is a missing alias error).

I have tested various online YAML checkers, and they vary between these two behaviors.

My reading of the YAML spec seems to support this being a valid alias name format (or at least it does not seem to say it should be rejected as a syntax error). I personally believe the SnakeYAML behavior is appropriate for the spec, even though this is very odd syntax to permit.

I need clarification from the spec maintainers about the correct error here:

* If the newer SnakeYAML behavior is correct, then libyaml is in error and should be fixed.
* If the libyaml behavior is correct, then SnakeYAML will need to make a change. In this case, I believe there should also be an update to the spec to indicate why this peculiar alias syntax should be rejected.

cc @asomov

**Comment by perlpunk** [comment]
libyaml restricted aliases to only alphanumeric and `-`. That's different from what the spec (1.1 and 1.2) says.
https://yaml.org/spec/1.2/spec.html#c-ns-anchor-property

So lbyaml is too restrictive here (although the spec was too permissive on the other hand).

For a future YAML version, the plan is to restrict the characters.

For that reason, I believe @ingydotnet  wants to keep libyaml's behaviour like it is.

**Comment by perlpunk** [comment]
See also https://github.com/yaml/libyaml/pull/170 (which had to be reverted) and he linked discussion in pyyaml.

**Comment by ingydotnet** [comment]
As @perlpunk said, the YAML 1.2 spec allowed too many characters (everything except whitespace and these chars `,[]{}`). See

* https://github.com/yaml/yaml-grammar/blob/master/yaml-spec-1.2.yaml#L1581
* https://github.com/yaml/yaml-grammar/blob/master/yaml-spec-1.2.yaml#L509

That means syntax characters like: `&*:|>` are allowed, which is not particularly useful to the language.

libyaml departed from the spec in several places that were just poorly specced. libyaml allow ascii word chars and dash.

In an upcoming version of YAML we are discussing extending the alias/reference syntax to include document paths.
Like `*/foo/0/bar`.

**Comment by headius** [comment]
Ok, thank you for the feedback! I will take this to SnakeYAML and encourage them to revisit this and match the restrictions found in libyaml more closely.

**Comment by headius** [comment]
I have filed an issue with SnakeYAML so @asomov can decide how to proceed.

https://bitbucket.org/asomov/snakeyaml/issues/485/alias-names-are-too-permissive-compared-to
