### ISSUE TITLE
Missing double quotes 

### ISSUE THREAD

**Issue by cagev** [yaml/libyaml#216]
yaml config: 

pipe:
  pipe_host: "127.0.0.1"
  pipe_port: 22223

after parse : 

=VAL :pipe
+MAP
=VAL :pipe_host
=VAL "127.0.0.1
=VAL :pipe_port
=VAL :22223

missing end double quotes in "127.0.0.1

**Comment by perlpunk** [comment]
You probably forgot to mention the tool you are talking about, `tests/run-parser-test-suite`.

The output you see is correct. The format is:
`=VAL <quoting-type><value>`
where quoting-type is `"'|>:` and `:` stands for plain.

Note that the output is informal and might change in the future, depending on if the test-suite format changes.
