### ISSUE TITLE
Emitter emits extra space when emitting null values

### ISSUE THREAD

**Issue by ingydotnet** [yaml/libyaml#46]
If you look at
https://github.com/yaml/libyaml-test/blob/master/test/libyaml-emitter.skip#L4
you'll see that the emitter test skips 12 tests because libyaml emits an extra
space at the end of a line where an empty string is emitted for a null value.

Using underscore to show a space char, libyaml emits:

```
foo:_
bar:
-_
```

To emit this data:

```
{"foo":null,"bar":[null]}
```

This is obviously because libyaml emits a space right after `-` or `:` which is
right most of the time.

Depending on when the output buffer is actually flushed, we might be able to do
an easy fix of backing up before the space when we get to a null value. Need to
look at the code.

**Comment by david-a-wheeler** [comment]
Please don't create ending whitespace.  Many projects' git repos or continuous integration (CI) process will automatically reject trailing whitespace.  For example, the [CII best practices badge](https://github.com/linuxfoundation/cii-best-practices-badge] CI process run "git diff --check" to find any trailing whitespace & rejects commits that include them.

**Comment by juanibiapina** [comment]
This looks like a long standing bug. The rails solution simply removes trailing whitespace after generating the file. Why not fixed it directly here?

**Comment by perlpunk** [comment]
I created a PR for fixing this: #186

It was easier than I thought, because the emitter does not output the space directly after the `:` and `-`.

**Comment by perlpunk** [comment]
Released 0.2.5!

**Comment by david-a-wheeler** [comment]
Thank you!
