### ISSUE TITLE
How to modify an existing Yaml File?

### ISSUE THREAD

**Issue by nidhhoggr** [yaml/libyaml#51]
Pardon me, but C is no my first language and I am having a really hard time grasping how to simply modify a node in a yaml file. My current approach, which may be entirely wrong is to parse the yaml file, loop through the events to output scalar data, modify the event scalar data if possible and emit it to a file (ideally the same file). Is this possible and if so can someone please point me to an example?

**Comment by nidhhoggr** [comment]
Here is the code:

```
    while (!done)
    {
        /* Get the next token. */

        if (!yaml_parser_parse(&parser, &event))
            goto parser_error;

        //yaml_parser_scan(&parser, &token);

        /* Check if this is the stream end. */

        if(beginServerNodes && event.type == 8) {
          beginServerNodes = 0;
        }

        if (event.type == YAML_SCALAR_EVENT) {
          if(beginServerNodes == 1) {
            //I WANT TO MODIFY THIS VALUE
            printf("%s\n", event.data.scalar.value);
          }
          if(strcmp("servers",event.data.scalar.value) == 0) {
            beginServerNodes = 1;
          }
        }

        if (event.type == YAML_STREAM_END_EVENT) {
            done = 1;
        }
        /* Emit the token. */

        if (!yaml_emitter_emit(&emitter, &event))
            goto emitter_error;
    }

    yaml_parser_delete(&parser);
    yaml_emitter_delete(&emitter);
```

**Comment by ingydotnet** [comment]
@nidhhoggr Take a look at these test programs I wrote recently:

https://github.com/yaml/libyaml/tree/master/tests/run-test-suite/src

You should be aware that your emitted yaml will probably not match the style of the input yaml. Comments will be discarded, etc.

Good luck. Closing this for now.

**Comment by nidhhoggr** [comment]
@ingydotnet thanks for pointing me to that code. If anyone has a similar issue I was able to modify the mode with the emitter loop with the following code:

            yaml_char_t newHost[] = "10.132.16.48:6379:1 redis-001";
            event.data.scalar.value = strdup(newHost);
            event.data.scalar.length = strlen(newHost);
