### ISSUE TITLE
difficult to use in program

### ISSUE THREAD

**Issue by jingshaoqi** [yaml/libyaml#61]
no example parse a document ,so difficult to use in our program,

for example,how to parse follows document , 

- name: Ogre
  position: [0, 5, 0]
  powers:
    - name: Club
      damage: 10
    - name: Fist
      damage: 8
- name: Dragon
  position: [1, 0, 10]
  powers:
    - name: Fire Breath
      damage: 25
    - name: Claws
      damage: 15
- name: Wizard
  position: [5, -3, 0]
  powers:
    - name: Acid Rain
      damage: 50
    - name: Staff
      damage: 3

**Comment by perlpunk** [comment]
You might wanna have a look at https://github.com/yaml/libyaml/blob/master/tests/run-test-suite/src/libyaml-parser.c
This is a script that parses the given input file and turns events into a format sitable for yaml-test-suite.
That should get you going.
If not, please reopen the issue.
