### ISSUE TITLE
libyaml allows illegal single-quote escape

### ISSUE THREAD

**Issue by headius** [yaml/libyaml#68]
libyaml appears to allow a single-quote escape sequence that is NOT allowed by YAML 1.1+.

From the spec, at http://yaml.org/spec/1.1/#id872840, you can see that double quote is a valid escape but single quote is not.

This has been reported as a JRuby bug multiple times because MRI (C Ruby) uses libyaml for its YAML engine. See jruby/jruby#2199, jruby/jruby#4847, and https://bugs.ruby-lang.org/issues/14096.

At this time, neither we nor the YAML library we use (SnakeYAML) plan to support this illegal character. I think it would be best for all YAML consumers if libyaml stuck to the spec here.

**Comment by perlpunk** [comment]
Created PR #74

**Comment by perlpunk** [comment]
PR #74 merged

**Comment by ingydotnet** [comment]
@perlpunk This should be closed now, right? Closing...
